spring:
  application:
    name: recipeScanner
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    problemdetails:
      enabled: true

ocr:
  language: "eng"

server:
  error:
    include-stacktrace: never
    include-message: never
